import type { Metadata } from 'next';
import { getLocale } from 'next-intl/server';
import { Geist, Geist_Mono, Noto_Sans, Tajawal } from 'next/font/google';
import { LocaleToggle } from '@/components/Local/locale-toggle';
import { ThemeProvider } from '@/components/Theme/theme-provider';
import { ThemeToggle } from '@/components/Theme/theme-toggle';
import './globals.css';
import { Locale } from '@/i18n/i18n.config';
import { Button } from '@/components/ui/button';
import { signOut, auth } from '@/lib/auth';
import { QueryProvider } from '@/components/providers/query-provider';

const notoSans = Noto_Sans({ variable: '--font-sans' });

const tajawal = Tajawal({
	variable: '--font-ar',
	subsets: ['arabic'],
	weight: ['200', '300', '400', '500', '700', '800', '900'],
});

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'easy-zakat',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = await (getLocale() as Promise<Locale>);
	const dir = locale === 'ar' ? 'rtl' : 'ltr';
	const langFont = locale === 'ar' ? tajawal : notoSans;
	const session = await auth();
	return (
		<html
			lang={locale}
			dir={dir}
			className={langFont.variable}
			suppressHydrationWarning
		>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<QueryProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<div className="fixed top-4 right-4 z-50 flex gap-2">
							<ThemeToggle />
							<LocaleToggle currentLocale={locale} />
							{session?.accessToken ? (
								<form
									action={async () => {
										'use server';
										await signOut({ redirectTo: '/' });
									}}
								>
									<Button variant="outline" type="submit">
										Sign Out
									</Button>
								</form>
							) : (
								<Button variant="outline" onClick={() => {}}>
									Sign In
								</Button>
							)}
						</div>

						{children}
					</ThemeProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
